package com.yiyekeji.studentmanager.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "STUDENT".
 */
public class Student implements Parcelable {

    private boolean isSelect;
    private Long id;

    public boolean isSelect() {
        return isSelect;
    }

    public void setSelect(boolean select) {
        isSelect = select;
    }

    private String name;
    private String age;
    private String sex;
    private String birthDay;
    private String studentId;
    private String headImg;
    private String nation;
    private String phone;
    private String note;

    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    public Student(Long id, String name, String age, String sex, String birthDay, String studentId, String headImg, String nation, String phone, String note) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.birthDay = birthDay;
        this.studentId = studentId;
        this.headImg = headImg;
        this.nation = nation;
        this.phone = phone;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    public String getNation() {
        return nation;
    }

    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeByte(this.isSelect ? (byte) 1 : (byte) 0);
        dest.writeValue(this.id);
        dest.writeString(this.name);
        dest.writeString(this.age);
        dest.writeString(this.sex);
        dest.writeString(this.birthDay);
        dest.writeString(this.studentId);
        dest.writeString(this.headImg);
        dest.writeString(this.nation);
        dest.writeString(this.phone);
        dest.writeString(this.note);
    }

    protected Student(Parcel in) {
        this.isSelect = in.readByte() != 0;
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.name = in.readString();
        this.age = in.readString();
        this.sex = in.readString();
        this.birthDay = in.readString();
        this.studentId = in.readString();
        this.headImg = in.readString();
        this.nation = in.readString();
        this.phone = in.readString();
        this.note = in.readString();
    }

    public static final Parcelable.Creator<Student> CREATOR = new Parcelable.Creator<Student>() {
        @Override
        public Student createFromParcel(Parcel source) {
            return new Student(source);
        }

        @Override
        public Student[] newArray(int size) {
            return new Student[size];
        }
    };
}
